### ISSUE TITLE
why I cannt install r4pde?

### ISSUE THREAD

**Issue by lucianhuang** [emdelponte/r4pde#1]
It shows that information.
Does anyone can give me advice, plz.

* installing *source* package ‘r4pde’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘Icens’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘r4pde’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/r4pde’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/kf/38cmhf_j41ggsf3949x5mx900000gn/T//RtmpUIyLnk/file786b7d8ae09f/r4pde_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by emdelponte** [comment]
Try the following code to install the package:    if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

BiocManager::install("Icens")

install.packages(interval)

devtools::install_github('emdelponte/r4pde', force=TRUE)

**Comment by lucianhuang** [comment]
Thanks a lot. Prof. Emerson M Del Ponte.
Your suggestions are constructive. 

However, I think that R package "Icens" might cause wrong.
I try to deal with this mistake by code 

--
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Icens")
--
and it shows me that

--
Warning message:
package(s) not installed when version(s) same as or greater than current; use `force = TRUE` to
  re-install: 'Icens' 
--
so I code 

--
install.packages("Icens", force = TRUE)
--
and it shows me that
--
Warning in install.packages :
  package ‘Icens’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
--
So, what should I do to fix this mistake?
Thank you for your assistance.






> if (!require("BiocManager", quietly = TRUE))
+     install.packages("BiocManager")
Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.2 (2023-10-31)
> 
> BiocManager::install("Icens")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package =
"BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.2 (2023-10-31)
Old packages: 'DBI'
Update all/some/none? [a/s/n]: 
Update all/some/none? [a/s/n]: install.packages(interval)
Update all/some/none? [a/s/n]: 
Update all/some/none? [a/s/n]: devtools::install_github('emdelponte/r4pde', force=TRUE)
Update all/some/none? [a/s/n]: 
a
trying URL 'https://cran.rstudio.com/bin/macosx/big-sur-arm64/contrib/4.3/DBI_1.2.0.tgz'
Content type 'application/x-gzip' length 822755 bytes (803 KB)
==================================================
downloaded 803 KB


The downloaded binary packages are in
	/var/folders/kf/38cmhf_j41ggsf3949x5mx900000gn/T//RtmpP0FZaI/downloaded_packages
Warning message:
package(s) not installed when version(s) same as or greater than current; use `force = TRUE` to
  re-install: 'Icens'

**Comment by harryeslick** [comment]
Hi @lucianhuang ,
Im finding it a bit hard to understand your post because of how the markdown is rendered, you may want to review your formatting.   

But I think you may just need to install {Icens} using:
`BiocManager::install("Icens", force = TRUE)`  
rather than:  
`install.packages("Icens", force = TRUE)`


I followed the original instructions without a problem, ( skipping `install.packages(interval)`  which didn't work). I am using R version 4.3.1.

**Comment by lucianhuang** [comment]
Sorry my friend, it's bad formatting.

Your suggestion is helpful and I install r4pde successfully.

I appreciate @harryeslick and @emdelponte's  help very much.
I believe I can continue learning the content of R for Plant Disease Epidemiology.

I code
"BiocManager::install("Icens", force = TRUE)"
and code
"if (!require(remotes)) {
  install.packages("remotes")
}
remotes::install_github("emdelponte/r4pde")"


The former message：

_Firstly, I code_ 
"if (!require("BiocManager", quietly = TRUE))
install.packages("BiocManager")
BiocManager::install("Icens")"

_and R tell me that_
"Warning message:
package(s) not installed when version(s) same as or greater than current; use force = TRUE to
re-install: 'Icens'"

_So I code that_
"install.packages("Icens", force = TRUE)"

_and it shows me that_
"package ‘Icens’ is not available for this version of R
A version of this package for your version of R might be available elsewhere,
see the ideas at https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages"
